/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppInfo: typeof import('./src/components/steps/appInfo.vue')['default']
    AppSetting: typeof import('./src/components/steps/appSetting.vue')['default']
    CheckboxItem: typeof import('./src/components/Inputs/checkboxItem.vue')['default']
    Compile: typeof import('./src/components/steps/compile.vue')['default']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    FileSelect: typeof import('./src/components/Inputs/fileSelect.vue')['default']
    Float: typeof import('@headlessui-float/vue')['Float']
    Frame: typeof import('./src/components/frame.vue')['default']
    IntroPage: typeof import('./src/components/steps/IntroPage.vue')['default']
    ListItemMaker: typeof import('./src/components/ListItemMaker.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverOverlay: typeof import('@headlessui/vue')['PopoverOverlay']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    RadioGroup: typeof import('@headlessui/vue')['RadioGroup']
    RadioGroupDescription: typeof import('@headlessui/vue')['RadioGroupDescription']
    RadioGroupLabel: typeof import('@headlessui/vue')['RadioGroupLabel']
    RadioGroupOption: typeof import('@headlessui/vue')['RadioGroupOption']
    RadioList: typeof import('./src/components/Inputs/radioList.vue')['default']
    SplashScreeenSetting: typeof import('./src/components/steps/splashScreeenSetting.vue')['default']
    Steps: typeof import('./src/components/steps.vue')['default']
    TextInput: typeof import('./src/components/Inputs/textInput.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    WebpageSetting: typeof import('./src/components/steps/webpageSetting.vue')['default']
    WebPageSetting: typeof import('./src/components/steps/webPageSetting.vue')['default']
    WebpPageSetting: typeof import('./src/components/steps/webpPageSetting.vue')['default']
  }
}
