/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppInfo: typeof import('./src/components/steps/appInfo.vue')['default']
    AppSetting: typeof import('./src/components/steps/appSetting.vue')['default']
    FileSelect: typeof import('./src/components/Inputs/fileSelect.vue')['default']
    Frame: typeof import('./src/components/frame.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverOverlay: typeof import('@headlessui/vue')['PopoverOverlay']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    RadioGroup: typeof import('@headlessui/vue')['RadioGroup']
    RadioGroupDescription: typeof import('@headlessui/vue')['RadioGroupDescription']
    RadioGroupLabel: typeof import('@headlessui/vue')['RadioGroupLabel']
    RadioGroupOption: typeof import('@headlessui/vue')['RadioGroupOption']
    SplashScreeenSetting: typeof import('./src/components/steps/splashScreeenSetting.vue')['default']
    Steps: typeof import('./src/components/steps.vue')['default']
    TextInput: typeof import('./src/components/Inputs/textInput.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
